### ISSUE TITLE
Input and target data

### ISSUE THREAD

**Issue by mrqorib** [THUNLP-MT/Voting4SC#1]
Hi,

I want to thank you for your great work and thank you for making your code public.
I would like to reproduce your research, and I appreciate that your code is easy to run, but I would like to verify that I'm running the code correctly. Would you mind sharing the input data (including the output of each single MT system that are passed to the model) along with the target data that are used in your experiments, so that I could try to train the model with the actual data myself? Thank you!

Warm regards,
Reza

**Comment by xc-kiwiberry** [comment]
Dear Reza,

Thank you for your attention. 
The dataset of the ZH-EN task from LDC is not publicly available.
The hypotheses of the EN-DE task is generated by FAIR's pre-trained model ([link1](https://github.com/pytorch/fairseq/blob/master/examples/translation/README.md), [link2](https://github.com/pytorch/fairseq/blob/master/examples/pay_less_attention_paper/README.md)) and easy-to-run [THUMT](https://github.com/THUNLP-MT/THUMT) toolkit with decode_alpha=0.6 and beam_size=4.

best wishes,
Xuancheng Huang
